# Generated by Django 2.0.5 on 2018-11-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=60, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('cust_type', models.CharField(blank=True, max_length=10, null=True)),
                ('winbox', models.CharField(blank=True, max_length=60, null=True)),
                ('lat', models.CharField(blank=True, max_length=60, null=True)),
                ('lng', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
