# Generated by Django 2.0.5 on 2018-11-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='sitesurvey_ok',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
