# Generated by Django 2.0.5 on 2018-11-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20181113_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='postalcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
