# Generated by Django 2.0.5 on 2018-11-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20181127_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='cust_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='sitesurvey_ok',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
