# Generated by Django 2.0.2 on 2018-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20181127_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='ap_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='ccq_rx',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='ccq_tx',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='rssi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='snr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
