# Generated by Django 2.0.2 on 2018-12-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20181207_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='neighbours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
